name: Python Unit test CI/CD

# Triggers the workflow on pushes to 'main' and all pull requests
on:
  push:
    branches:
      - main
  pull_request:                            ## Event pull push 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   ## Container for deployment
    environment:
      name: Development
    steps:
    - name: Checkout repository code                    ## checkout repository code
      # Action to clone the repository content
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      # Action to set up a specific Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
      

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ⚙️ Run Tests and Linting (Placeholder)
      # In a real app, you would run 'pytest', 'flake8', or 'mypy' here.
      run: |
        echo "Running static analysis and unit tests..."
        # Example of a test command:
        # pip install pytest
        pytest
        echo "Tests and linting passed successfully."


